name: async_button
description: Buttons for asyncronous onPressed function
version: 1.0.0-beta.1
homepage: https://github.com/abhisheksrocks/async_button

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0